spring:
  application:
    name: ms-pedido-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

